### ISSUE TITLE
Cant add new hub (android devices)

### ISSUE THREAD

**Issue by 3chapo3** [cloudsyjared/SmartThings-MiLight#3]
I have followed all the instructions and have installed everything. I set the bridge up as per instructions.  When I open the smart app and get to the zones section and input 4 nothing happens.  I do not get 4 zones to name.  I have tried other numbers and moving fields but nothing happens.  When I hit done it tells me an error has occured.  It's the same issue the other guy was having in the forums.  Any help would be greatly appreciated.  I would add logs, but I have no idea how to do that.  I am new to this whole thing.

Thanks,
Chris

**Comment by cloudsyjared** [comment]
Is this on an android device ?

**Comment by 3chapo3** [comment]
Yes.  Nexus 6.  I don't think it matters, but its rooted.

**Comment by cloudsyjared** [comment]
Of course it matters.

**Comment by cloudsyjared** [comment]
OK, I tested it on my Android tablet. Hit 1 and hit "done", does a field become available?

**Comment by 3chapo3** [comment]
1 did not work but 0 did. I was able to add the four zones. It never gave me the option to set up new connected devices though. So there is something I am missing.

**Comment by cloudsyjared** [comment]
Sorry, what setup are you looking for? Can you explain the 0 to me please so I can understand the bug more?

**Comment by 3chapo3** [comment]
I tried hitting 1 and done as you had directed but that didn't work so I tried 0.  That worked to open up the fields for me.  I thought the directions stated there would be 5 new connected devices to configure. I could be mistaken. I am mobile right now. The lights aren't turning on. I think its something with the milight hub setup.

**Comment by 3chapo3** [comment]
Never mind on the connected devices.  I was wrong on that.  I am trying to upload a photo of my milight hub setup but not having any luck.

**Comment by cloudsyjared** [comment]
@3chapo3 I have made some changes around how zones are named in my dev branch. I do not have access to an Android tablet to test until later today.

**Comment by cloudsyjared** [comment]
I have merged a fix into the master branch. Basically, go to your SmartApps page, and click update from repo, and ensure you mark publish. Uninstall everything, use the new code, and let me know how it goes.

**Comment by 3chapo3** [comment]
Well it appears that my hub just died.  It's not seeing any wifi networks.  Started last night after a reset.  A reset to factory settings didn't fix the problem so it looks like I will have to get a new hub.  As soon as I do I will test the new code and let you know.  Thanks for your help!

**Comment by 3chapo3** [comment]
And I spoke too soon.  The hub decided to work again after another reset.  I deleted and reinstalled the code.  I set everything up, which went without a hitch.  It's working good.  I am able to control all four zones.  When I turn a zone off the lights flash a few colors a few times before going off, but they do go off.  I am able to change brightness as well as color from Smartthings.  If there is something else you need me to test let me know.  Awesome work!

**Comment by cloudsyjared** [comment]
Ah ok that's a good bug report and I think I know why. The color changing issue probably stops if you change the color of your bulbs to whatever then back to white.

**Comment by 3chapo3** [comment]
It seems that the issue with the color is only using the lights for the first time.  After that they function normally.  My lights are only RGB so I guess you can say they work with RGB now.  I didn't realize until I went through the forum a little bit ago that they probably wouldn't work with RGB.  Again, thanks for all the work.

Chris

**Comment by cloudsyjared** [comment]
#4
